language: ruby
rvm:
  - 2.6.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # https://github.com/typhoeus/typhoeus/issues/568
before_script:
  - yarn install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./build --url-ignore "/burden.cc/"