# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jekyll-bulma-blog
description: A fully-featured blog boilerplate for Jekyll made extraordinary with the help of Bulma.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll-bulma-blog.burden.cc" # the base hostname & protocol for your site, e.g. http://example.com
analytics-id: 
thanks: "/thanks/" # after form submitted, send visitor here
email-key: 1nBbONFhyVzmU7rWSaquH6ICGTcQ0olKX5jk9Y2e8fsiLJPvAdE4RMpZDtw3gx
email-encoded: JAHr9Jr@wq9lmdw.JAl

# Social settings
github: burden/jekyll-bulma-blog
maintainers:
  - burden

# Build settings
plugins:
  - kramdown
  - uglifier
  - jekyll-assets
  - jekyll-archives
  - jekyll-compose
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

source: src
destination: www
markdown: kramdown
    
compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

paginate: 4
paginate_path: /:num/
permalink: /:categories/:title/

jekyll-archives:
  enabled: ['categories', 'tags', 'year']
  layout: default
  layouts:
    year: archive-date
    category: archive-catalog
    tag: archive-catalog
  permalinks:
    year: '/:year/'
    tag: '/tag/:name/'
    category: '/:name/'
    
include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
